#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'europa:~/fptf-badges/'

ssh europa "\
cd ~/fptf-badges
npm i
npm update
forever-service delete fptf-badges
forever-service install fptf-badges --start -s index.js"
